all: indexer

indexer: main.o word_struct.o
	gcc -o indexer main.o word_struct.o

main.o: main.c word_struct.o read_files.o hashtable.o
	gcc -o main.o main.c -c -W -Wall -pedatic

word_struct.o: ./libs/word_struct.c ./libs/word_struct.h
	gcc -o word_struct.o word_struct.c -c -W -Wall -pedatic

read_files.o: ./libs/read_files/read_files.c word_struct.o
	gcc -o read_files.o ./libs/read_files/read_files.c word_struct.o -c -W -Wall -pedatic

hashtable.o: libs/hash_table libs/hash_table word_struct.o
	gcc -o hash_tabletable.o ./libs/hash_tabletable/hash.c -c -W -Wall -pedatic

hashsimples.o: ./hashsimples/hashsimples.c ./hashsimples/hashsimples.h word_struct.o
	gcc -o simple_hash.o ./simple_hash/simple_hash.c -c -W -Wall -pedatic

hashlinked.o: ./hashlinked/hashlinked.c ./hashlinked/hashlinked.h word_struct.o
	gcc -o hash_with_linked_list.o ./hash_with_linked_list/hash_with_linked_list.c -c -W -Wall -pedatic

clean:
	rm -rf *.o *~indexer



